//
//  ChainLogo.swift
//  ProjectName
//
//  Created by AuthorName on 12/2/16.
//  Copyright © 2016 CompanyName. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//
//  This code was generated by Trial version of PaintCode, therefore cannot be used for commercial purposes.
//



import UIKit

public class ChainLogo : NSObject {

    //// Drawing Methods

    public dynamic class func drawLogo() {
        // This code was generated by Trial version of PaintCode, therefore cannot be used for commercial purposes.
        // http://www.paintcodeapp.com
        
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()!
        
        //// Color Declarations
        let green = UIColor(red: 0.408, green: 0.635, blue: 0.514, alpha: 1.000)
        
        //// Bezier Drawing
        let bezierPath = UIBezierPath()
        UIColor.black.setStroke()
        bezierPath.lineWidth = 1
        bezierPath.stroke()
        
        
        //// icoTab1.pdf Group
        //// Bezier 2 Drawing
        let bezier2Path = UIBezierPath()
        bezier2Path.move(to: CGPoint(x: 52, y: 91))
        bezier2Path.addCurve(to: CGPoint(x: 73.65, y: 84.78), controlPoint1: CGPoint(x: 52, y: 91), controlPoint2: CGPoint(x: 63.52, y: 84.78))
        bezier2Path.addCurve(to: CGPoint(x: 100, y: 89.15), controlPoint1: CGPoint(x: 85.39, y: 84.77), controlPoint2: CGPoint(x: 100, y: 89.15))
        bezier2Path.addLine(to: CGPoint(x: 86.56, y: 58.47))
        bezier2Path.addCurve(to: CGPoint(x: 69.4, y: 55.03), controlPoint1: CGPoint(x: 86.56, y: 58.47), controlPoint2: CGPoint(x: 80.03, y: 55.49))
        bezier2Path.addCurve(to: CGPoint(x: 52, y: 59.95), controlPoint1: CGPoint(x: 58.77, y: 54.57), controlPoint2: CGPoint(x: 52, y: 59.95))
        bezier2Path.addLine(to: CGPoint(x: 52, y: 91))
        bezier2Path.close()
        bezier2Path.move(to: CGPoint(x: 55.4, y: 98.05))
        bezier2Path.addCurve(to: CGPoint(x: 57.98, y: 100), controlPoint1: CGPoint(x: 56.93, y: 98.86), controlPoint2: CGPoint(x: 57.98, y: 100))
        bezier2Path.addCurve(to: CGPoint(x: 71.89, y: 95.89), controlPoint1: CGPoint(x: 57.98, y: 100), controlPoint2: CGPoint(x: 63.64, y: 95.89))
        bezier2Path.addCurve(to: CGPoint(x: 83.6, y: 96.69), controlPoint1: CGPoint(x: 75.37, y: 95.89), controlPoint2: CGPoint(x: 79.55, y: 96.06))
        bezier2Path.addCurve(to: CGPoint(x: 98.62, y: 100), controlPoint1: CGPoint(x: 91.41, y: 97.91), controlPoint2: CGPoint(x: 98.62, y: 100))
        bezier2Path.addLine(to: CGPoint(x: 100, y: 95.4))
        bezier2Path.addCurve(to: CGPoint(x: 73.8, y: 91), controlPoint1: CGPoint(x: 100, y: 95.4), controlPoint2: CGPoint(x: 85.41, y: 91))
        bezier2Path.addCurve(to: CGPoint(x: 52, y: 97.09), controlPoint1: CGPoint(x: 62.2, y: 91), controlPoint2: CGPoint(x: 52, y: 97.09))
        bezier2Path.addCurve(to: CGPoint(x: 55.4, y: 98.05), controlPoint1: CGPoint(x: 52, y: 97.09), controlPoint2: CGPoint(x: 53.86, y: 97.24))
        bezier2Path.close()
        bezier2Path.move(to: CGPoint(x: 48, y: 91))
        bezier2Path.addCurve(to: CGPoint(x: 26.35, y: 84.78), controlPoint1: CGPoint(x: 48, y: 91), controlPoint2: CGPoint(x: 36.48, y: 84.78))
        bezier2Path.addCurve(to: CGPoint(x: 0, y: 89.15), controlPoint1: CGPoint(x: 14.61, y: 84.77), controlPoint2: CGPoint(x: 0, y: 89.15))
        bezier2Path.addLine(to: CGPoint(x: 13.44, y: 58.47))
        bezier2Path.addCurve(to: CGPoint(x: 30.6, y: 55.03), controlPoint1: CGPoint(x: 13.44, y: 58.47), controlPoint2: CGPoint(x: 19.97, y: 55.49))
        bezier2Path.addCurve(to: CGPoint(x: 48, y: 59.95), controlPoint1: CGPoint(x: 41.23, y: 54.57), controlPoint2: CGPoint(x: 48, y: 59.95))
        bezier2Path.addLine(to: CGPoint(x: 48, y: 91))
        bezier2Path.close()
        bezier2Path.move(to: CGPoint(x: 44.6, y: 98.05))
        bezier2Path.addCurve(to: CGPoint(x: 42.02, y: 100), controlPoint1: CGPoint(x: 43.07, y: 98.86), controlPoint2: CGPoint(x: 42.02, y: 100))
        bezier2Path.addCurve(to: CGPoint(x: 28.11, y: 95.89), controlPoint1: CGPoint(x: 42.02, y: 100), controlPoint2: CGPoint(x: 36.36, y: 95.89))
        bezier2Path.addCurve(to: CGPoint(x: 16.4, y: 96.69), controlPoint1: CGPoint(x: 24.63, y: 95.89), controlPoint2: CGPoint(x: 20.45, y: 96.06))
        bezier2Path.addCurve(to: CGPoint(x: 1.38, y: 100), controlPoint1: CGPoint(x: 8.59, y: 97.91), controlPoint2: CGPoint(x: 1.38, y: 100))
        bezier2Path.addLine(to: CGPoint(x: 0, y: 95.4))
        bezier2Path.addCurve(to: CGPoint(x: 26.2, y: 91), controlPoint1: CGPoint(x: 0, y: 95.4), controlPoint2: CGPoint(x: 14.59, y: 91))
        bezier2Path.addCurve(to: CGPoint(x: 48, y: 97.09), controlPoint1: CGPoint(x: 37.8, y: 91), controlPoint2: CGPoint(x: 48, y: 97.09))
        bezier2Path.addCurve(to: CGPoint(x: 44.6, y: 98.05), controlPoint1: CGPoint(x: 48, y: 97.09), controlPoint2: CGPoint(x: 46.14, y: 97.24))
        bezier2Path.close()
        green.setFill()
        bezier2Path.fill()
        
        
        //// Group 2
        //// Rectangle Drawing
        context.saveGState()
        context.translateBy(x: 52.11, y: 26.41)
        context.rotate(by: -30 * CGFloat.pi/180)
        
        let rectanglePath = UIBezierPath(rect: CGRect(x: -13.84, y: -22.5, width: 27.68, height: 45))
        green.setFill()
        rectanglePath.fill()
        
        context.restoreGState()

    }

    public dynamic class func drawPlaceholder(size: CGSize = CGSize(width: 66, height: 66)) -> UIImage {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()!
        
        //// Color Declarations
        let fillColor = UIColor(red: 0.408, green: 0.635, blue: 0.514, alpha: 1.000)
        
        //// Frames
        let frame = CGRect(x: 0, y: 0, width: size.width, height: size.height)
        
        
        //// Group 2
        context.saveGState()
        context.translateBy(x: frame.minX + 0.50000 * frame.width, y: frame.minY + 0.51515 * frame.height)
        
        
        
        //// Bezier Drawing
        context.saveGState()
        context.translateBy(x: 0.34, y: 0.87)
        
        let bezierPath = UIBezierPath()
        bezierPath.move(to: CGPoint(x: 0.46, y: 15.92))
        bezierPath.addCurve(to: CGPoint(x: 9.12, y: 13.7), controlPoint1: CGPoint(x: 0.46, y: 15.92), controlPoint2: CGPoint(x: 5.07, y: 13.7))
        bezierPath.addCurve(to: CGPoint(x: 19.66, y: 15.26), controlPoint1: CGPoint(x: 13.82, y: 13.7), controlPoint2: CGPoint(x: 19.66, y: 15.26))
        bezierPath.addLine(to: CGPoint(x: 14.29, y: 4.32))
        bezierPath.addCurve(to: CGPoint(x: 7.42, y: 3.09), controlPoint1: CGPoint(x: 14.29, y: 4.32), controlPoint2: CGPoint(x: 11.67, y: 3.26))
        bezierPath.addCurve(to: CGPoint(x: 0.46, y: 4.85), controlPoint1: CGPoint(x: 3.17, y: 2.93), controlPoint2: CGPoint(x: 0.46, y: 4.85))
        bezierPath.addLine(to: CGPoint(x: 0.46, y: 15.92))
        bezierPath.close()
        bezierPath.move(to: CGPoint(x: 1.82, y: 18.43))
        bezierPath.addCurve(to: CGPoint(x: 2.86, y: 19.13), controlPoint1: CGPoint(x: 2.44, y: 18.72), controlPoint2: CGPoint(x: 2.86, y: 19.13))
        bezierPath.addCurve(to: CGPoint(x: 8.42, y: 17.66), controlPoint1: CGPoint(x: 2.86, y: 19.13), controlPoint2: CGPoint(x: 5.12, y: 17.66))
        bezierPath.addCurve(to: CGPoint(x: 13.1, y: 17.95), controlPoint1: CGPoint(x: 9.81, y: 17.66), controlPoint2: CGPoint(x: 11.48, y: 17.72))
        bezierPath.addCurve(to: CGPoint(x: 19.11, y: 19.13), controlPoint1: CGPoint(x: 16.23, y: 18.38), controlPoint2: CGPoint(x: 19.11, y: 19.13))
        bezierPath.addLine(to: CGPoint(x: 19.66, y: 17.49))
        bezierPath.addCurve(to: CGPoint(x: 9.18, y: 15.92), controlPoint1: CGPoint(x: 19.66, y: 17.49), controlPoint2: CGPoint(x: 13.83, y: 15.92))
        bezierPath.addCurve(to: CGPoint(x: 0.46, y: 18.09), controlPoint1: CGPoint(x: 4.54, y: 15.92), controlPoint2: CGPoint(x: 0.46, y: 18.09))
        bezierPath.addCurve(to: CGPoint(x: 1.82, y: 18.43), controlPoint1: CGPoint(x: 0.46, y: 18.09), controlPoint2: CGPoint(x: 1.21, y: 18.14))
        bezierPath.close()
        bezierPath.move(to: CGPoint(x: -1.14, y: 15.92))
        bezierPath.addCurve(to: CGPoint(x: -9.8, y: 13.7), controlPoint1: CGPoint(x: -1.14, y: 15.92), controlPoint2: CGPoint(x: -5.75, y: 13.7))
        bezierPath.addCurve(to: CGPoint(x: -20.34, y: 15.26), controlPoint1: CGPoint(x: -14.49, y: 13.7), controlPoint2: CGPoint(x: -20.34, y: 15.26))
        bezierPath.addLine(to: CGPoint(x: -14.96, y: 4.32))
        bezierPath.addCurve(to: CGPoint(x: -8.1, y: 3.09), controlPoint1: CGPoint(x: -14.96, y: 4.32), controlPoint2: CGPoint(x: -12.35, y: 3.26))
        bezierPath.addCurve(to: CGPoint(x: -1.14, y: 4.85), controlPoint1: CGPoint(x: -3.85, y: 2.93), controlPoint2: CGPoint(x: -1.14, y: 4.85))
        bezierPath.addLine(to: CGPoint(x: -1.14, y: 15.92))
        bezierPath.close()
        bezierPath.move(to: CGPoint(x: -2.5, y: 18.43))
        bezierPath.addCurve(to: CGPoint(x: -3.53, y: 19.13), controlPoint1: CGPoint(x: -3.11, y: 18.72), controlPoint2: CGPoint(x: -3.53, y: 19.13))
        bezierPath.addCurve(to: CGPoint(x: -9.09, y: 17.66), controlPoint1: CGPoint(x: -3.53, y: 19.13), controlPoint2: CGPoint(x: -5.8, y: 17.66))
        bezierPath.addCurve(to: CGPoint(x: -13.78, y: 17.95), controlPoint1: CGPoint(x: -10.48, y: 17.66), controlPoint2: CGPoint(x: -12.16, y: 17.72))
        bezierPath.addCurve(to: CGPoint(x: -19.79, y: 19.13), controlPoint1: CGPoint(x: -16.9, y: 18.38), controlPoint2: CGPoint(x: -19.79, y: 19.13))
        bezierPath.addLine(to: CGPoint(x: -20.34, y: 17.49))
        bezierPath.addCurve(to: CGPoint(x: -9.86, y: 15.92), controlPoint1: CGPoint(x: -20.34, y: 17.49), controlPoint2: CGPoint(x: -14.5, y: 15.92))
        bezierPath.addCurve(to: CGPoint(x: -1.14, y: 18.09), controlPoint1: CGPoint(x: -5.22, y: 15.92), controlPoint2: CGPoint(x: -1.14, y: 18.09))
        bezierPath.addCurve(to: CGPoint(x: -2.5, y: 18.43), controlPoint1: CGPoint(x: -1.14, y: 18.09), controlPoint2: CGPoint(x: -1.88, y: 18.14))
        bezierPath.close()
        bezierPath.usesEvenOddFillRule = true
        fillColor.setFill()
        bezierPath.fill()
        
        context.restoreGState()
        
        
        //// Group
        context.saveGState()
        context.translateBy(x: 0.34, y: 0.87)
        
        context.beginTransparencyLayer(auxiliaryInfo: nil)
        
        //// Clip Clip
        let clipPath = UIBezierPath(roundedRect: CGRect(x: -4.81, y: -8.02, width: 9.63, height: 16.05), cornerRadius: 1)
        var clipTransformation = CGAffineTransform.identity
        clipTransformation = clipTransformation.translatedBy(x: -0.98, y: -11.52)
        clipTransformation = clipTransformation.rotated(by: -30 * CGFloat.pi/180)
        clipPath.apply(clipTransformation)
        clipPath.addClip()
        
        
        //// Rectangle Drawing
        context.saveGState()
        context.translateBy(x: -0.98, y: -11.52)
        context.rotate(by: -30 * CGFloat.pi/180)
        
        let rectanglePath = UIBezierPath(rect: CGRect(x: -8.82, y: -12.04, width: 17.64, height: 24.07))
        fillColor.setFill()
        rectanglePath.fill()
        
        context.restoreGState()
        
        
        context.endTransparencyLayer()
        
        context.restoreGState()
        
        
        
        context.restoreGState()
    
        let image = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()
        
        return image!
    }

    @objc public enum ResizingBehavior: Int {
        case aspectFit /// The content is proportionally resized to fit into the target rectangle.
        case aspectFill /// The content is proportionally resized to completely fill the target rectangle.
        case stretch /// The content is stretched to match the entire target rectangle.
        case center /// The content is centered in the target rectangle, but it is NOT resized.

        public func apply(rect: CGRect, target: CGRect) -> CGRect {
            if rect == target || target == CGRect.zero {
                return rect
            }

            var scales = CGSize.zero
            scales.width = abs(target.width / rect.width)
            scales.height = abs(target.height / rect.height)

            switch self {
                case .aspectFit:
                    scales.width = min(scales.width, scales.height)
                    scales.height = scales.width
                case .aspectFill:
                    scales.width = max(scales.width, scales.height)
                    scales.height = scales.width
                case .stretch:
                    break
                case .center:
                    scales.width = 1
                    scales.height = 1
            }

            var result = rect.standardized
            result.size.width *= scales.width
            result.size.height *= scales.height
            result.origin.x = target.minX + (target.width - result.width) / 2
            result.origin.y = target.minY + (target.height - result.height) / 2
            return result
        }
    }
}
